# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 拂杨柳
subtitle:
description: 从哪里跌倒，就从哪爬起来！
author: fuyl
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://chenjunwen.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# 搜索服务
algolia:
  applicationID: 'G59F9PHJPH'
  apiKey: 'fd45c74158859bdf2ed2d2afaf4c1e21'
  adminApiKey: 'dfc480dacd70cd57bff6d074a62e6716'
  indexName: 'blog'
  chunkSize: 5000
# 错误  Please set an `HEXO_ALGOLIA_INDEXING_KEY` environment variable to enable content indexing.
# 更新数据：hexo algolia
#解决办法：64a0439c0082400a6ef4897be62a9668
      #重新在https://www.algolia.com/apps/G59F9PHJPH/api-keys/restricted申请多一个拥有Add records, Delete records, List indices, Delete index权限的API Key
      #然后环境变量 set HEXO_ALGOLIA_INDEXING_KEY=API KEY(刚生成的)


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia-plus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/chenjunwen/chenjunwen.github.io.git
  branch: master


jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true